In [1]:
import pandas as pd

In [5]:
# df = pd.read_csv('./result_qpp_union/bi-directional/mt5_3.csv')
# df = pd.read_csv('./result_qpp_union/perplexity/bm25_3.csv')
df = pd.read_csv('./result_qpp_union/mt5_3.csv')
df_o = df.copy()
df = df[((df.alpha==0)|(df.alpha==0.5)|(df.alpha==1))&(df.window_size==10)]

In [29]:
df_o.sort_values(by=['tau'], ascending=False)

,retriever,k,qpp_method,window_size,alpha,r,p1(r),tau,p1(tau),num_of_queries,with_0shot_posterior
787,mt5,3,bertQPP,5,0.75,0.403628,0.000041,0.303694,0.000010,97,True
777,mt5,3,bertQPP,5,0.70,0.408961,0.000032,0.303265,0.000011,97,True
767,mt5,3,bertQPP,5,0.65,0.411559,0.000028,0.301976,0.000012,97,True
3097,mt5,3,bertQPP,16,0.75,0.392836,0.000069,0.299399,0.000014,97,True
797,mt5,3,bertQPP,5,0.80,0.395993,0.000059,0.298969,0.000014,97,True
...,...,...,...,...,...,...,...,...,...,...,...
844,mt5,3,nqc,6,0.00,0.154428,0.130966,-0.079467,0.248844,97,False
634,mt5,3,nqc,5,0.00,0.154428,0.130966,-0.079467,0.248844,97,False
214,mt5,3,nqc,3,0.00,0.154428,0.130966,-0.079467,0.248844,97,False
1894,mt5,3,nqc,11,0.00,0.154428,0.130966,-0.079467,0.248844,97,False
3150,mt5,3,0shot_pos,16,1.00,-0.249340,0.013781,-0.186426,0.006825,97,True

In [30]:
df[(df.alpha==0.5)&(df.with_0shot_posterior==True)]

,retriever,k,qpp_method,window_size,alpha,r,p1(r),tau,p1(tau),num_of_queries,with_0shot_posterior
1781,mt5,3,spatial,10,0.5,0.281241,0.005262,0.210911,0.002209,97,True
1783,mt5,3,a_ratio,10,0.5,0.168043,0.099909,0.062285,0.366086,97,True
1785,mt5,3,nqc,10,0.5,0.345392,0.000530,0.252148,0.000253,97,True
1787,mt5,3,bertQPP,10,0.5,0.368480,0.000204,0.270619,0.000086,97,True
1789,mt5,3,bertQPP(QV),10,0.5,0.342177,0.000602,0.234536,0.000666,97,True

In [31]:
df[(df.alpha==0.5)&(df.with_0shot_posterior==False)]

,retriever,k,qpp_method,window_size,alpha,r,p1(r),tau,p1(tau),num_of_queries,with_0shot_posterior
1780,mt5,3,spatial,10,0.5,0.357336,0.000327,0.237543,0.000567,97,False
1782,mt5,3,a_ratio,10,0.5,0.116250,0.256821,0.005155,0.940374,97,False
1784,mt5,3,nqc,10,0.5,0.320350,0.001379,0.216924,0.001645,97,False
1786,mt5,3,bertQPP,10,0.5,0.338302,0.000701,0.237973,0.000554,97,False
1788,mt5,3,bertQPP(QV),10,0.5,0.297716,0.003060,0.201031,0.003532,97,False

In [32]:
df[(df.alpha==0)&(df.with_0shot_posterior==True)]

,retriever,k,qpp_method,window_size,alpha,r,p1(r),tau,p1(tau),num_of_queries,with_0shot_posterior
1681,mt5,3,spatial,10,0.0,0.265354,0.008619,0.202320,0.003326,97,True
1683,mt5,3,a_ratio,10,0.0,0.149700,0.143326,0.036512,0.596229,97,True
1685,mt5,3,nqc,10,0.0,0.154727,0.130215,-0.073454,0.286471,97,True
1687,mt5,3,bertQPP,10,0.0,0.260262,0.010036,0.214347,0.001868,97,True
1689,mt5,3,bertQPP(QV),10,0.0,0.210732,0.038276,0.173540,0.011794,97,True

In [33]:
df[(df.alpha==0)&(df.with_0shot_posterior==False)]

,retriever,k,qpp_method,window_size,alpha,r,p1(r),tau,p1(tau),num_of_queries,with_0shot_posterior
1680,mt5,3,spatial,10,0.0,0.290285,0.003923,0.180842,0.008685,97,False
1682,mt5,3,a_ratio,10,0.0,0.098037,0.339404,-0.013316,0.846777,97,False
1684,mt5,3,nqc,10,0.0,0.154428,0.130966,-0.079467,0.248844,97,False
1686,mt5,3,bertQPP,10,0.0,0.207361,0.041550,0.168385,0.014547,97,False
1688,mt5,3,bertQPP(QV),10,0.0,0.142561,0.163624,0.119845,0.082019,97,False

In [34]:
df[(df.alpha==1)&(df.qpp_method=='nqc')]

,retriever,k,qpp_method,window_size,alpha,r,p1(r),tau,p1(tau),num_of_queries,with_0shot_posterior
1884,mt5,3,nqc,10,1.0,0.295730,0.003272,0.196306,0.004391,97,False
1885,mt5,3,nqc,10,1.0,0.322585,0.001271,0.228522,0.000913,97,True

In [35]:
df[df.with_0shot_posterior==False].sort_values(by=['tau'], ascending=False).head(5)

,retriever,k,qpp_method,window_size,alpha,r,p1(r),tau,p1(tau),num_of_queries,with_0shot_posterior
1786,mt5,3,bertQPP,10,0.5,0.338302,0.000701,0.237973,0.000554,97,False
1780,mt5,3,spatial,10,0.5,0.357336,0.000327,0.237543,0.000567,97,False
1784,mt5,3,nqc,10,0.5,0.320350,0.001379,0.216924,0.001645,97,False
1788,mt5,3,bertQPP(QV),10,0.5,0.297716,0.003060,0.201031,0.003532,97,False
1880,mt5,3,spatial,10,1.0,0.295730,0.003272,0.196306,0.004391,97,False

In [36]:
df[df.with_0shot_posterior].sort_values(by=['tau'], ascending=False).head(5)

,retriever,k,qpp_method,window_size,alpha,r,p1(r),tau,p1(tau),num_of_queries,with_0shot_posterior
1787,mt5,3,bertQPP,10,0.5,0.368480,0.000204,0.270619,0.000086,97,True
1785,mt5,3,nqc,10,0.5,0.345392,0.000530,0.252148,0.000253,97,True
1789,mt5,3,bertQPP(QV),10,0.5,0.342177,0.000602,0.234536,0.000666,97,True
1881,mt5,3,spatial,10,1.0,0.322585,0.001271,0.228522,0.000913,97,True
1887,mt5,3,bertQPP,10,1.0,0.322585,0.001271,0.228522,0.000913,97,True

In [26]:
df[(df.alpha==0)&(df.window_size==10)&(df.with_0shot_posterior==False)]

,retriever,k,qpp_method,window_size,alpha,r,p1(r),tau,p1(tau),num_of_queries,with_0shot_posterior
1680,bm25,3,spatial,10,0.0,0.384525,0.000101,0.219931,0.001416,97,False
1682,bm25,3,a_ratio,10,0.0,0.313620,0.001760,0.120704,0.079850,97,False
1684,bm25,3,nqc,10,0.0,0.015030,0.883825,-0.023625,0.731725,97,False
1686,bm25,3,bertQPP,10,0.0,0.255573,0.011518,0.186856,0.006698,97,False
1688,bm25,3,bertQPP(QV),10,0.0,0.247476,0.014529,0.185567,0.007086,97,False

In [16]:
df[(df.alpha==0)&(df.window_size==2)&(df.with_0shot_posterior)]

Empty DataFrame
Columns: [retriever, k, qpp_method, window_size, alpha, r, p1(r), tau, p1(tau), num_of_queries, with_0shot_posterior]
Index: []

In [9]:
df[(df.alpha==1)&(df.qpp_method=='spatial')&(df.with_0shot_posterior==False)]

,retriever,k,qpp_method,window_size,alpha,r,p1(r),tau,p1(tau),num_of_queries,with_0shot_posterior
1880,mt5,3,spatial,10,1.0,0.251897,0.01281,0.123711,0.072623,97,False

In [10]:
df[(df.alpha==1)&(df.qpp_method=='spatial')&(df.with_0shot_posterior)]

,retriever,k,qpp_method,window_size,alpha,r,p1(r),tau,p1(tau),num_of_queries,with_0shot_posterior
1881,mt5,3,spatial,10,1.0,0.293448,0.003532,0.147766,0.032012,97,True