In [1]:
import pandas as pd

In [46]:
mt5_5 = pd.read_csv('./result_qpp_union/tct_5.csv')

In [47]:
mt5_5.head()

,retriever,k,qpp_method,window_size,alpha,r,p1(r),tau,p1(tau),num_of_queries
0,tct,5,spatial,2,0.0,0.263011,0.009247,0.110395,0.109165,97
1,tct,5,a_ratio,2,0.0,0.256666,0.011156,0.105241,0.126721,97
2,tct,5,nqc,2,0.0,0.259758,0.010187,0.072595,0.292145,97
3,tct,5,spatial,2,0.1,0.264967,0.008720,0.113832,0.098570,97
4,tct,5,a_ratio,2,0.1,0.257492,0.010890,0.099656,0.148142,97

In [51]:
mt5_5.tau.max()

0.1585051546391753

In [49]:
mt5_5[(mt5_5.alpha==0)&(mt5_5.qpp_method=='spatial')]

,retriever,k,qpp_method,window_size,alpha,r,p1(r),tau,p1(tau),num_of_queries
0,tct,5,spatial,2,0.0,0.263011,0.009247,0.110395,0.109165,97
33,tct,5,spatial,3,0.0,0.301124,0.002725,0.104811,0.128278,97
66,tct,5,spatial,4,0.0,0.317125,0.001551,0.146907,0.033024,97
99,tct,5,spatial,5,0.0,0.288471,0.004164,0.111254,0.106435,97
132,tct,5,spatial,6,0.0,0.251335,0.013018,0.110395,0.109165,97
165,tct,5,spatial,7,0.0,0.258664,0.010521,0.115120,0.094816,97
198,tct,5,spatial,8,0.0,0.263108,0.009220,0.129296,0.060625,97
231,tct,5,spatial,9,0.0,0.280078,0.005461,0.121993,0.076684,97

In [50]:
mt5_5[(mt5_5.alpha==0.3)&(mt5_5.qpp_method=='spatial')]

,retriever,k,qpp_method,window_size,alpha,r,p1(r),tau,p1(tau),num_of_queries
9,tct,5,spatial,2,0.3,0.266029,0.008445,0.115550,0.093590,97
42,tct,5,spatial,3,0.3,0.299247,0.002905,0.116838,0.089989,97
75,tct,5,spatial,4,0.3,0.313280,0.001781,0.157646,0.022160,97
108,tct,5,spatial,5,0.3,0.286363,0.004461,0.114261,0.097306,97
141,tct,5,spatial,6,0.3,0.252640,0.012539,0.103093,0.134656,97
174,tct,5,spatial,7,0.3,0.260398,0.009996,0.116838,0.089989,97
207,tct,5,spatial,8,0.3,0.263677,0.009065,0.125859,0.067796,97
240,tct,5,spatial,9,0.3,0.276745,0.006068,0.122423,0.075652,97